### ISSUE TITLE
Rotation for square/rectangle

### ISSUE THREAD

**Issue by Ampmau** [noquinn/pixel-shape-generator#1]
I noticed there isn't a option for rotation for the square or rectangle, can you add one please? I like to do a lot of angled builds and it would really help

**Comment by noquinn** [comment]
Just added a rotatable rectangle ([582a99b](https://github.com/noquinn/pixel-shape-generator/commit/582a99bb2aead9bec65211c6df20c6a0d440a253)) 🙂

Is that what you were looking for, or are you asking for the ability to rotate the superelljpse?

**Comment by Ampmau** [comment]
> Just added a rotatable rectangle ([582a99b](https://github.com/noquinn/pixel-shape-generator/commit/582a99bb2aead9bec65211c6df20c6a0d440a253)) 🙂
> 
> Is that what you were looking for, or are you asking for the ability to rotate the superellipse?

I was asking for the ability to cause form what I saw it doesn't have it

Image: 
![Pixel Shape Generator - Brave 8_7_2024 8_25_53 PM](https://github.com/user-attachments/assets/35287d9a-54c8-4d3d-bf95-9d4a3f9950e5) 

it just has something called exponent
